spring:
  datasource:
    url: jdbc:h2:file:./data/paymentdb;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  thymeleaf:
    cache: false

logging:
  level:
    com.paytech.payment: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
    reactor.netty.http.client: DEBUG

paytech:
  api:
    base-url: https://engine-sandbox.pay.tech/api/v1
    bearer-token: cAmmvalAikARkB81fgxgMtnMbEdNbuWa
    timeout: 30s